### ISSUE TITLE
Oz failing to render

### ISSUE THREAD

**Issue by Folcon** [metasoarous/oz#117]
Not sure if this is a bug, but if I try to render [this example from the vega lite docs in oz](https://vega.github.io/vega-lite/docs/repeat.html#multi-series-line-chart-with-repeated-layers), it renders the page, but produces a broken graph. Viewing via "Open in Vega Editor" shows correct output.

[GIST](https://gist.github.com/Folcon/1539712d093b5063dee9be7b7badf0ba)

Example of what is rendered in Oz:
<img width="276" alt="Screenshot 2020-04-25 at 02 36 39" src="https://user-images.githubusercontent.com/123055/80268275-b1407380-869d-11ea-9747-f225f0afa627.png">

What the editor shows:
<img width="673" alt="Screenshot 2020-04-25 at 02 37 44" src="https://user-images.githubusercontent.com/123055/80268286-c9b08e00-869d-11ea-97f6-1e556dbcb2c0.png">

**Comment by metasoarous** [comment]
Hi Folcon

Thanks for reporting this.

I would look at what is coming up for height when you import the graph. Not sure why that wouldn't be working if the vega-lite spec is the same. Might want to check to see if there's a vega-lite/vega/vega-embed version difference; That has caused discrepancy in the past.

I'm hoping to improve the debugging utilities to make this sort of thing easier to sort out in the future.

Thanks again!

Chris

**Comment by Folcon** [comment]
Hi @metasoarous, not 100% certain what you mean by what is coming up in height? Do you mean canvas height?

Here's what I get from the vega editor version:
```
<canvas width="802" height="484" class="marks" style="width: 401px; height: 242px;"></canvas>
```

vs oz:
```
<canvas width="428" height="132" class="marks" style="width: 214px;height: 66px;"></canvas>
```

Regarding `deps.edn`:
```
metasoarous/oz {:mvn/version "1.6.0-alpha6"
                        :exclusions [cider/cider-nrepl]}
```

You're right that doing `clojure -Stree | grep vega` gives me:
```
cljsjs/vega 5.9.0-0
cljsjs/vega-lite 4.0.2-0
cljsjs/vega-tooltip 0.20.0-0
cljsjs/vega-embed 6.0.0-0
```
So there's scope to update stuff perhaps?

It certainly doesn't seem to match _your_ `package.json` file:
```
"vega": "^5.9.1",
"vega-lite": "^4.0.2",
"vega-embed": "^6.2.2",
"vega-tooltip": "^0.20.0"
```

So perhaps when you do an update?

**Comment by metasoarous** [comment]
Hi @Folcon.

Sorry for leaving you hanging for a bit here, and thanks for your patience.

Please see `1.6.0-alpha8` and let me know if that works for you.

Thanks!

**Comment by mtravers** [comment]
I was having a similar problem. I tried upgrading from alpha6 to alpha8, but that results in errors like this when starting up the server:
```
java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)
	at ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73)
	at ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73)
	at ring.middleware.cookies$write_cookies$iter__13461__13465$fn__13466.invoke(cookies.clj:92)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at ring.middleware.cookies$set_cookies.invokeStatic(cookies.clj:102)
	at ring.middleware.cookies$set_cookies.invoke(cookies.clj:95)
	at ring.middleware.cookies$cookies_response.invokeStatic(cookies.clj:121)
	at ring.middleware.cookies$cookies_response.doInvoke(cookies.clj:114)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at ring.middleware.session$session_response.invokeStatic(session.clj:70)
	at ring.middleware.session$session_response.doInvoke(session.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at ring.middleware.session$wrap_session$fn__13634.invoke(session.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__13674.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__13740.invoke(nested_params.clj:84)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__14007.invoke(multipart_params.clj:117)
	at ring.middleware.params$wrap_params$fn__14039.invoke(params.clj:64)
	at ring.middleware.cookies$wrap_cookies$fn__13501.invoke(cookies.clj:161)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__14232.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource$fn__14083.invoke(resource.clj:28)
	at ring.middleware.content_type$wrap_content_type$fn__14181.invoke(content_type.clj:30)
	at ring.middleware.default_charset$wrap_default_charset$fn__14204.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__14141.invoke(not_modified.clj:52)
	at ring.middleware.x_headers$wrap_x_header$fn__12451.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__12451.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__12451.invoke(x_headers.clj:22)
	at ring.middleware.cljsjs$wrap_cljsjs$fn__14386.invoke(cljsjs.clj:50)
	at ring.middleware.gzip$wrap_gzip$fn__14348.invoke(gzip.clj:100)
	at clojure.lang.Var.invoke(Var.java:384)
	at aleph.http.server$handle_request$fn__34882$f__29967__auto____34883.invoke(server.clj:158)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__29849$f__29850.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by mtravers** [comment]
Note: upgrading to alpha31 (the latest on clojars) made the Ring problem go away but the original problem still stands (trying to generate a vega tree plot; only one dot shows up; but it looks fine in the editor)

**Comment by metasoarous** [comment]
Hey @Folcon. I'm going to go ahead and close this for now since I haven't heard back on it, but please let me know if this continues to be a problem.

Thanks again!

**Comment by Folcon** [comment]
@metasoarous Sorry for not getting back to you, I've just not been fiddling with the environment subsequently to sending that message. Thanks for doing the fix however =)...

**Comment by metasoarous** [comment]
@Folcon No worries at all! Please do let me know if you get back to it though. Thanks!
