### ISSUE TITLE
Following README starting from scratch got runtime error: java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)

### ISSUE THREAD

**Issue by yubrshen** [metasoarous/oz#125]
I'm following the instructions:
```
Assuming you're starting from scratch, first add oz to your leiningen project dependencies

[metasoarous/oz "1.6.0-alpha13"]

Next, require oz and start the plot server as follows:

(require '[oz.core :as oz])

(oz/start-server!)
```
when executing `(oz/start-server!)` I got the error at web page of http://localhost:10666/:
`java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)`
(The full stack trace is at the end of this post.)

Here is the content of the project.clj:
```
(defproject oz-try "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [metasoarous/oz "1.6.0-alpha13"]]
  :main ^:skip-aot oz-try.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```
However, with cloning `https://github.com/metasoarous/oz`
running the same function `(oz/start-server!)` worked fine.

I suspect that the dependency of my oz-try project may not enough.
But I'm not able to figure out the corresponding dependencies of your project for dev/user.clj

Here are the full stack trace at web page of http://localhost:10666/:
```
java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)
	at ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73)
	at ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73)
	at ring.middleware.cookies$write_cookies$iter__1354__1358$fn__1359.invoke(cookies.clj:92)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at ring.middleware.cookies$set_cookies.invokeStatic(cookies.clj:102)
	at ring.middleware.cookies$set_cookies.invoke(cookies.clj:95)
	at ring.middleware.cookies$cookies_response.invokeStatic(cookies.clj:121)
	at ring.middleware.cookies$cookies_response.doInvoke(cookies.clj:114)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at ring.middleware.session$session_response.invokeStatic(session.clj:70)
	at ring.middleware.session$session_response.doInvoke(session.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at ring.middleware.session$wrap_session$fn__1527.invoke(session.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__1567.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__1633.invoke(nested_params.clj:84)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__1900.invoke(multipart_params.clj:117)
	at ring.middleware.params$wrap_params$fn__1932.invoke(params.clj:64)
	at ring.middleware.cookies$wrap_cookies$fn__1394.invoke(cookies.clj:161)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__2125.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource$fn__1976.invoke(resource.clj:28)
	at ring.middleware.content_type$wrap_content_type$fn__2074.invoke(content_type.clj:30)
	at ring.middleware.default_charset$wrap_default_charset$fn__2097.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__2034.invoke(not_modified.clj:52)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.cljsjs$wrap_cljsjs$fn__2279.invoke(cljsjs.clj:50)
	at ring.middleware.gzip$wrap_gzip$fn__2241.invoke(gzip.clj:100)
	at clojure.lang.Var.invoke(Var.java:384)
	at aleph.http.server$handle_request$fn__23917$f__18174__auto____23918.invoke(server.clj:158)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__18056$f__18057.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by metasoarous** [comment]
Hi @yubrshen. Thanks for reporting this.

Can you please let me know whether this works for you if you just directly call `oz/view!` without calling `oz/start-server!`? I don't usually manually call `start-server!`, so I'm wondering if that's where the problem might be.

Certainly curious that it only works in one context and not the other.

Thanks again!

**Comment by mgryzz** [comment]
Hi @yubrshen, i had exactly the same issue when i tried oz for the first time today.
This seems to be a problem with ring/ring-defaults and an old ring/ring-core version (also see https://github.com/ring-clojure/ring-defaults/pull/22).

As a workaround I added `[ring/ring-core "1.8.1"]` to the dependencies of my project.clj which resolved the error for me:

**Comment by yubrshen** [comment]
> Hi @yubrshen. Thanks for reporting this.
> 
> Can you please let me know whether this works for you if you just directly call `oz/view!` without calling `oz/start-server!`? I don't usually manually call `start-server!`, so I'm wondering if that's where the problem might be.
> 
> Certainly curious that it only works in one context and not the other.
> 
> Thanks again!

Hi @metasoarous, thanks for replying to me promptly!

I did one more experiment, of directly evaluating `(oz/view! line-plot)`, it seemed that the failure is the same.

Here is the stack trace at the web page, `http://localhost:10666/` 
```
java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)
	at ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73)
	at ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73)
	at ring.middleware.cookies$write_cookies$iter__1354__1358$fn__1359.invoke(cookies.clj:92)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at ring.middleware.cookies$set_cookies.invokeStatic(cookies.clj:102)
	at ring.middleware.cookies$set_cookies.invoke(cookies.clj:95)
	at ring.middleware.cookies$cookies_response.invokeStatic(cookies.clj:121)
	at ring.middleware.cookies$cookies_response.doInvoke(cookies.clj:114)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at ring.middleware.session$session_response.invokeStatic(session.clj:70)
	at ring.middleware.session$session_response.doInvoke(session.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at ring.middleware.session$wrap_session$fn__1527.invoke(session.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__1567.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__1633.invoke(nested_params.clj:84)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__1900.invoke(multipart_params.clj:117)
	at ring.middleware.params$wrap_params$fn__1932.invoke(params.clj:64)
	at ring.middleware.cookies$wrap_cookies$fn__1394.invoke(cookies.clj:161)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__2125.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource$fn__1976.invoke(resource.clj:28)
	at ring.middleware.content_type$wrap_content_type$fn__2074.invoke(content_type.clj:30)
	at ring.middleware.default_charset$wrap_default_charset$fn__2097.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__2034.invoke(not_modified.clj:52)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)
	at ring.middleware.cljsjs$wrap_cljsjs$fn__2279.invoke(cljsjs.clj:50)
	at ring.middleware.gzip$wrap_gzip$fn__2241.invoke(gzip.clj:100)
	at clojure.lang.Var.invoke(Var.java:384)
	at aleph.http.server$handle_request$fn__23917$f__18174__auto____23918.invoke(server.clj:158)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__18056$f__18057.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
At the repl shell, here is the error:
```
20-07-28 04:04:06 yubrshen-Alienware-15-R3 ERROR [oz.core:1114] - error sending plot to server: clojure.lang.ExceptionInfo: clj-http: status 500 {:cached nil, :request-time 71, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x65917302 "org.apache.http.impl.client.InternalHttpClient@65917302"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Internal Server Error", :headers {"Content-Type" "text/plain", "Server" "Aleph/0.4.4", "Connection" "Close", "Date" "Tue, 28 Jul 2020 04:04:06 GMT", "content-length" "2882"}, :orig-content-encoding nil, :status 500, :length 2882, :body "java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)\n\tat ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73)\n\tat ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73)\n\tat ring.middleware.cookies$write_cookies$iter__1354__1358$fn__1359.invoke(cookies.clj:92)\n\tat clojure.lang.LazySeq.sval(LazySeq.java:42)\n\tat clojure.lang.LazySeq.seq(LazySeq.java:51)\n\tat clojure.lang.RT.seq(RT.java:535)\n\tat clojure.core$seq__5402.invokeStatic(core.clj:137)\n\tat clojure.core$dorun.invokeStatic(core.clj:3133)\n\tat clojure.core$doall.invokeStatic(core.clj:3148)\n\tat clojure.core$doall.invoke(core.clj:3148)\n\tat ring.middleware.cookies$set_cookies.invokeStatic(cookies.clj:102)\n\tat ring.middleware.cookies$set_cookies.invoke(cookies.clj:95)\n\tat ring.middleware.cookies$cookies_response.invokeStatic(cookies.clj:121)\n\tat ring.middleware.cookies$cookies_response.doInvoke(cookies.clj:114)\n\tat clojure.lang.RestFn.invoke(RestFn.java:410)\n\tat ring.middleware.session$session_response.invokeStatic(session.clj:70)\n\tat ring.middleware.session$session_response.doInvoke(session.clj:64)\n\tat clojure.lang.RestFn.invoke(RestFn.java:442)\n\tat ring.middleware.session$wrap_session$fn__1527.invoke(session.clj:103)\n\tat ring.middleware.keyword_params$wrap_keyword_params$fn__1567.invoke(keyword_params.clj:35)\n\tat ring.middleware.nested_params$wrap_nested_params$fn__1633.invoke(nested_params.clj:84)\n\tat ring.middleware.multipart_params$wrap_multipart_params$fn__1900.invoke(multipart_params.clj:117)\n\tat ring.middleware.params$wrap_params$fn__1932.invoke(params.clj:64)\n\tat ring.middleware.cookies$wrap_cookies$fn__1394.invoke(cookies.clj:161)\n\tat ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__2125.invoke(absolute_redirects.clj:47)\n\tat ring.middleware.resource$wrap_resource$fn__1976.invoke(resource.clj:28)\n\tat ring.middleware.content_type$wrap_content_type$fn__2074.invoke(content_type.clj:30)\n\tat ring.middleware.default_charset$wrap_default_charset$fn__2097.invoke(default_charset.clj:31)\n\tat ring.middleware.not_modified$wrap_not_modified$fn__2034.invoke(not_modified.clj:52)\n\tat ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)\n\tat ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)\n\tat ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)\n\tat ring.middleware.cljsjs$wrap_cljsjs$fn__2279.invoke(cljsjs.clj:50)\n\tat ring.middleware.gzip$wrap_gzip$fn__2241.invoke(gzip.clj:100)\n\tat clojure.lang.Var.invoke(Var.java:384)\n\tat aleph.http.server$handle_request$fn__23917$f__18174__auto____23918.invoke(server.clj:158)\n\tat clojure.lang.AFn.run(AFn.java:22)\n\tat io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)\n\tat manifold.executor$thread_factory$reify__18056$f__18057.invoke(executor.clj:44)\n\tat clojure.lang.AFn.run(AFn.java:22)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n", :trace-redirects []}
20-07-28 04:04:06 yubrshen-Alienware-15-R3 ERROR [oz.core:1115] - Try using a different port?
clojure.lang.ExceptionInfo: clj-http: status 500 {:cached nil, :request-time 71, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x65917302 "org.apache.http.impl.client.InternalHttpClient@65917302"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Internal Server Error", :headers {"Content-Type" "text/plain", "Server" "Aleph/0.4.4", "Connection" "Close", "Date" "Tue, 28 Jul 2020 04:04:06 GMT", "content-length" "2882"}, :orig-content-encoding nil, :status 500, :length 2882, :body "java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)\n\tat ring.middleware.cookies$write_attr_map.invokeStatic(cookies.clj:73)\n\tat ring.middleware.cookies$write_attr_map.invoke(cookies.clj:73)\n\tat ring.middleware.cookies$write_cookies$iter__1354__1358$fn__1359.invoke(cookies.clj:92)\n\tat clojure.lang.LazySeq.sval(LazySeq.java:42)\n\tat clojure.lang.LazySeq.seq(LazySeq.java:51)\n\tat clojure.lang.RT.seq(RT.java:535)\n\tat clojure.core$seq__5402.invokeStatic(core.clj:137)\n\tat clojure.core$dorun.invokeStatic(core.clj:3133)\n\tat clojure.core$doall.invokeStatic(core.clj:3148)\n\tat clojure.core$doall.invoke(core.clj:3148)\n\tat ring.middleware.cookies$set_cookies.invokeStatic(cookies.clj:102)\n\tat ring.middleware.cookies$set_cookies.invoke(cookies.clj:95)\n\tat ring.middleware.cookies$cookies_response.invokeStatic(cookies.clj:121)\n\tat ring.middleware.cookies$cookies_response.doInvoke(cookies.clj:114)\n\tat clojure.lang.RestFn.invoke(RestFn.java:410)\n\tat ring.middleware.session$session_response.invokeStatic(session.clj:70)\n\tat ring.middleware.session$session_response.doInvoke(session.clj:64)\n\tat clojure.lang.RestFn.invoke(RestFn.java:442)\n\tat ring.middleware.session$wrap_session$fn__1527.invoke(session.clj:103)\n\tat ring.middleware.keyword_params$wrap_keyword_params$fn__1567.invoke(keyword_params.clj:35)\n\tat ring.middleware.nested_params$wrap_nested_params$fn__1633.invoke(nested_params.clj:84)\n\tat ring.middleware.multipart_params$wrap_multipart_params$fn__1900.invoke(multipart_params.clj:117)\n\tat ring.middleware.params$wrap_params$fn__1932.invoke(params.clj:64)\n\tat ring.middleware.cookies$wrap_cookies$fn__1394.invoke(cookies.clj:161)\n\tat ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__2125.invoke(absolute_redirects.clj:47)\n\tat ring.middleware.resource$wrap_resource$fn__1976.invoke(resource.clj:28)\n\tat ring.middleware.content_type$wrap_content_type$fn__2074.invoke(content_type.clj:30)\n\tat ring.middleware.default_charset$wrap_default_charset$fn__2097.invoke(default_charset.clj:31)\n\tat ring.middleware.not_modified$wrap_not_modified$fn__2034.invoke(not_modified.clj:52)\n\tat ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)\n\tat ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)\n\tat ring.middleware.x_headers$wrap_x_header$fn__326.invoke(x_headers.clj:22)\n\tat ring.middleware.cljsjs$wrap_cljsjs$fn__2279.invoke(cljsjs.clj:50)\n\tat ring.middleware.gzip$wrap_gzip$fn__2241.invoke(gzip.clj:100)\n\tat clojure.lang.Var.invoke(Var.java:384)\n\tat aleph.http.server$handle_request$fn__23917$f__18174__auto____23918.invoke(server.clj:158)\n\tat clojure.lang.AFn.run(AFn.java:22)\n\tat io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)\n\tat manifold.executor$thread_factory$reify__18056$f__18057.invoke(executor.clj:44)\n\tat clojure.lang.AFn.run(AFn.java:22)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n", :trace-redirects []}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at clj_http.client$exceptions_response.invokeStatic(client.clj:245)
	at clj_http.client$exceptions_response.invoke(client.clj:236)
	at clj_http.client$wrap_exceptions$fn__27566.invoke(client.clj:254)
	at clj_http.client$wrap_accept$fn__27812.invoke(client.clj:737)
	at clj_http.client$wrap_accept_encoding$fn__27819.invoke(client.clj:759)
	at clj_http.client$wrap_content_type$fn__27806.invoke(client.clj:720)
	at clj_http.client$wrap_form_params$fn__27915.invoke(client.clj:961)
	at clj_http.client$wrap_nested_params$fn__27936.invoke(client.clj:995)
	at clj_http.client$wrap_flatten_nested_params$fn__27945.invoke(client.clj:1019)
	at clj_http.client$wrap_method$fn__27873.invoke(client.clj:895)
	at clj_http.cookies$wrap_cookies$fn__26853.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__27341.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__27953.invoke(client.clj:1048)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1176)
	at clj_http.client$request_STAR_.invoke(client.clj:1169)
	at clj_http.client$get.invokeStatic(client.clj:1182)
	at clj_http.client$get.doInvoke(client.clj:1178)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at oz.core$prepare_server_for_view_BANG_.invokeStatic(core.clj:278)
	at oz.core$prepare_server_for_view_BANG_.invoke(core.clj:268)
	at oz.core$view_BANG_.invokeStatic(core.clj:1109)
	at oz.core$view_BANG_.doInvoke(core.clj:1098)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at oz_try.core$eval45442.invokeStatic(form-init16706366798564663774.clj:29)
	at oz_try.core$eval45442.invoke(form-init16706366798564663774.clj:29)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7132)
	at clojure.core$eval.invokeStatic(core.clj:3214)
	at clojure.core$eval.invoke(core.clj:3210)
	at nrepl.middleware.interruptible_eval$evaluate$fn__32066$fn__32067.invoke(interruptible_eval.clj:82)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at nrepl.middleware.interruptible_eval$evaluate$fn__32066.invoke(interruptible_eval.clj:82)
	at clojure.main$repl$read_eval_print__9086$fn__9089.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9086.invoke(main.clj:437)
	at clojure.main$repl$fn__9095.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at refactor_nrepl.ns.slam.hound.regrow$wrap_clojure_repl$fn__41777.doInvoke(regrow.clj:20)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:79)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__32097$fn__32101.invoke(interruptible_eval.clj:145)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__32164$fn__32168.invoke(session.clj:202)
	at nrepl.middleware.session$session_exec$main_loop__32164.invoke(session.clj:201)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I agree with @mgryzz that it might be a failure of starting the web server, which might be implemented through ring. By reading your deps.edn at your oz repository, it seems that you have quite many dependencies to ring:
        ring {:mvn/version "1.7.1"}
        ring/ring-defaults {:mvn/version "0.3.2"}
        bk/ring-gzip {:mvn/version "0.3.0"}
        ring-cljsjs {:mvn/version "0.1.0"}

I'll try to add the dependency to ring for web server.

**Comment by yubrshen** [comment]
I confirmed that adding` [ring "1.7.1"]` to the dependencies in `project.clj`, then 
both ways of evaluation works as expected:
`(oz/view! line-plot)` alone launched the web page, and display the line chart
`(oz/start-server!)` just launched the web page;

**Comment by maersdal** [comment]
I had the same issue. Forcing up ring to 1.8.1 solved the problem for me.

**Comment by metasoarous** [comment]
Thank you all for your feedback here; Glad we have a workaround for this.

@maersdal Are you using `clj` & `deps.edn` or `lein` & `project.clj`? Also are you using the latest version of Oz?

FWIW, I'm using the `clj` & `deps.edn`. Wondering if there are dependency resolution discrepancies here. I need to update a number of dependencies though, so will try to get around to this at point, and we can see if this issue resolves.

Thanks again folks!

**Comment by maersdal** [comment]
Leiningen with 
[org.clojure/clojure "1.10.1"] and 
[metasoarous/oz "1.6.0-alpha26"]

**Comment by metasoarous** [comment]
Thanks for the feedback @maersdal. I'll try to get this updated soon, but in the meantime, I'll just point out that there's no time like the present to switch to `clj` & `deps.edn` :-)

**Comment by metasoarous** [comment]
Hi folks; Thanks for your patience here. Please try out `[metasoarous/oz "1.6.0-alpha27"]` and see if that works for you. If the problem persists for whatever reason, please feel free to reopen this issue.

Thanks again!

**Comment by metasoarous** [comment]
Hello again; In #132 I think we've isolated the issue here, and resolution should be present in `alpha29`. Please let me know if that works for you. Thanks!
