### ISSUE TITLE
fail to lein run

### ISSUE THREAD

**Issue by temco** [metasoarous/oz#41]
When I `lein run` (2.8.3, with the cider 0.20.0) in the root directory of the project on OSX 10.14.2, some errors were caught as follows:
```
Warning: implicit middleware found: cider-nrepl.plugin/middleware 
Please declare all middleware in :middleware as implicit loading is deprecated.
Compiling ClojureScript...
Compiling "resources/public/js/compiled/oz.js" from ["src/cljs"]...
Compiling "resources/public/js/compiled/oz.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:/Users/x/oz/target/cljsbuild-compiler-1/cljs/core.cljs {:file #object[java.io.File 0x466afa50 "/Users/x/oz/target/cljsbuild-compiler-1/cljs/core.cljs"]}
	at cljs.compiler$compile_file$fn__3822.invoke(compiler.cljc:1705)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1665)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1641)
	at cljs.closure$compile_file.invokeStatic(closure.clj:647)
	at cljs.closure$compile_file.invoke(closure.clj:625)
	at cljs.closure$fn__5294.invokeStatic(closure.clj:721)
	at cljs.closure$fn__5294.invoke(closure.clj:715)
	at cljs.closure$fn__5207$G__5200__5214.invoke(closure.clj:543)
	at cljs.closure$compile_from_jar.invokeStatic(closure.clj:694)
	at cljs.closure$compile_from_jar.invoke(closure.clj:684)
	at cljs.closure$fn__5298.invokeStatic(closure.clj:731)
	at cljs.closure$fn__5298.invoke(closure.clj:715)
	at cljs.closure$fn__5207$G__5200__5214.invoke(closure.clj:543)
	at cljs.closure$compile_sources$iter__5420__5424$fn__5425.invoke(closure.clj:1081)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:1077)
	at cljs.closure$compile_sources.invoke(closure.clj:1066)
	at cljs.closure$build.invokeStatic(closure.clj:2995)
	at cljs.closure$build.invoke(closure.clj:2903)
	at cljs.build.api$build.invokeStatic(api.clj:208)
	at cljs.build.api$build.invoke(api.clj:189)
	at cljs.build.api$build.invokeStatic(api.clj:195)
	at cljs.build.api$build.invoke(api.clj:189)
	at cljsbuild.compiler$compile_cljs$fn__33943.invoke(compiler.clj:66)
	at cljsbuild.compiler$compile_cljs.invokeStatic(compiler.clj:65)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:54)
	at cljsbuild.compiler$run_compiler.invokeStatic(compiler.clj:165)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:126)
	at user$eval34061$iter__34109__34113$fn__34114$fn__34140.invoke(form-init4346494109930367496.clj:1)
	at user$eval34061$iter__34109__34113$fn__34114.invoke(form-init4346494109930367496.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at user$eval34061.invokeStatic(form-init4346494109930367496.clj:1)
	at user$eval34061.invoke(form-init4346494109930367496.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No reader function for tag Inf {:type :reader-exception, :line 999, :column 14, :file "file:/Users/x/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/core.cljs"}
	at clojure.tools.reader.reader_types$reader_error.invokeStatic(reader_types.clj:331)
	at clojure.tools.reader.reader_types$reader_error.doInvoke(reader_types.clj:327)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.tools.reader$read_tagged.invokeStatic(reader.clj:824)
	at clojure.tools.reader$read_tagged.invoke(reader.clj:811)
	at clojure.tools.reader$read_dispatch.invokeStatic(reader.clj:71)
	at clojure.tools.reader$read_dispatch.invoke(reader.clj:66)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:872)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_tagged.invokeStatic(reader.clj:812)
	at clojure.tools.reader$read_tagged.invoke(reader.clj:811)
	at clojure.tools.reader$read_dispatch.invokeStatic(reader.clj:71)
	at clojure.tools.reader$read_dispatch.invoke(reader.clj:66)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read.invokeStatic(reader.clj:938)
	at clojure.tools.reader$read.invoke(reader.clj:915)
	at cljs.analyzer$forms_seq_STAR_$forms_seq___2593$fn__2594$fn__2595.invoke(analyzer.cljc:3938)
	at cljs.analyzer$forms_seq_STAR_$forms_seq___2593$fn__2594.invoke(analyzer.cljc:3931)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$next__5371.invoke(core.clj:64)
	at cljs.analyzer$analyze_file$fn__2699.invoke(analyzer.cljc:4388)
	at cljs.analyzer$analyze_file.invokeStatic(analyzer.cljc:4374)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:4332)
	at cljs.analyzer$analyze_file.invokeStatic(analyzer.cljc:4346)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:4332)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1415)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1405)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1592)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1585)
	at cljs.compiler$compile_file$fn__3822.invoke(compiler.cljc:1690)
	... 59 more
```
I don't know how to resolve this.

**Comment by temco** [comment]
sorry, when I remove the .lein/profiles.clj, it works
maybe I should scan why the profile caused the implicit middleware
