### ISSUE TITLE
Updating to core.async 0.7.559 throws exception on view!

### ISSUE THREAD

**Issue by kennyjwilli** [metasoarous/oz#90]
I updated to `org.clojure/core.async {:mvn/version "0.7.559"}` from `org.clojure/core.async  {:mvn/version "0.4.490"}` and now receive this exception after calling `view!`. 

```clojure
Exception in thread "async-dispatch-3" java.lang.IllegalArgumentException: No implementation of method: :close! of protocol: #'clojure.core.async.impl.protocols/Channel found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.core.async.impl.protocols$eval1504$fn__1505$G__1493__1510.invoke(protocols.clj:21)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:984)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
	at taoensso.sente$make_channel_socket_server_BANG_$send_fn__9693$fn__9855.invoke(sente.cljc:476)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__1742$fn__1743.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "async-dispatch-6" java.lang.IllegalArgumentException: No implementation of method: :close! of protocol: #'clojure.core.async.impl.protocols/Channel found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.core.async.impl.protocols$eval1504$fn__1505$G__1493__1510.invoke(protocols.clj:21)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:984)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__7629.invoke(ioc_macros.clj:991)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__1938.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__1742$fn__1743.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It sounds like sente is calling `async/close!` on `nil`, which is not a valid call. I have not dug into the relevant code in Oz or sente that would cause this to occur.

**Comment by metasoarous** [comment]
Hi @kennyjwilli. Thanks for reporting this. Can you please try using `1.6.0-alpha6` and see if this fixes things?

Thanks again!

**Comment by kennyjwilli** [comment]
`1.6.0-alpha6` works. Thank you!
